version: 3

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
  build:
    desc: Build puff binary
    cmds:
      - go1.25.3 build -o puff cmd/main.go
  run:
    desc: Run puff from source
    cmds:
      - go1.25.3 run cmd/main.go
  destroy:
    desc: Remove puff directory
    cmds:
      - rm -rf ~/.config/puff
  destroy-bins:
    desc: Remove puff bin/* and metadata.json
    cmds:
      - rm -rf ~/.config/puff/bin/*
      - rm -f ~/.config/puff/metadata.json
  metadata:
    desc: Read metadata.json
    cmds:
      - cat ~/.config/puff/metadata.json
